KmetApp/urls.py
from django.conf.urls import url

from . import views


app_name = 'KmetApp'

urlpatterns = [
    url(r'^home/', views.home, name='home'),
    url(r'^register_user/', views.register_user, name='register_user'),
    url(r'^logon/', views.logon, name='logon'),
    url(r'^logoff/', views.logoff, name='logoff'),
    url(r'^add_selling/', views.add_selling, name='add_selling'),
    url(r'^edit_user/', views.edit_user, name='edit_user'),
    url(r'^search_selling/', views.search_selling, name='search_selling'),
    url(r'^add_orderS/', views.add_orderS, name='add_orderS'),
    url(r'^my_sellings/', views.my_sellings, name='my_sellings'),
    url(r'^disable_selling/', views.disable_selling, name='disable_selling'),
    url(r'^add_basket/', views.add_basket, name='add_basket'),
    url(r'^search_basket/', views.search_basket, name='search_basket'),
    url(r'^my_OrderSellings/', views.my_OrderSellings, name='my_OrderSellings'),
    url(r'^undoneOrder/', views.undoneOrder, name='undoneOrder'),
    url(r'^doneOrder/', views.doneOrder, name='doneOrder'),
    url(r'^editSelling/', views.editSelling, name='editSelling'),
    url(r'^complete_orderSelling/', views.complete_orderSelling, name='complete_orderSelling'),
    url(r'^add_orderB/', views.add_orderB, name='add_orderB'),
    url(r'^disable_basket/', views.disable_basket, name='disable_basket'),
    url(r'^my_baskets/', views.my_baskets, name='my_baskets'),
    url(r'^editBasket/', views.editBasket, name='editBasket'),
    url(r'^my_OrderBasket/', views.my_OrderBasket, name='my_OrderBasket'),
    url(r'^undoneOrderB/', views.undoneOrderB, name='undoneOrderB'),
    url(r'^doneOrderB/', views.doneOrderB, name='doneOrderB'),
    url(r'^complete_orderBasket/', views.complete_orderBasket, name='complete_orderBasket'),
    


]

KmetSite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^app/', include('KmetApp.urls', namespace="KmetApp"))
]

KmetApp/models.py
from django.db import models
from django.contrib.auth.models import (BaseUserManager, AbstractBaseUser,
                                        PermissionsMixin)


class CustomUserManager(BaseUserManager):
    """ Custom Manager """
    def create_user(self, email, password=None):
        """ create user method"""
        if not email:
            raise ValueError("User more imet email!")

        email = email.lower()
        user = self.model(email=CustomUserManager.normalize_email(email))
        user.set_password(password)
        user.save(using=self._db)
        user.is_staff = False
        user.is_admin = False
        user.is_active = True
        return user

    def create_superuser(self, email, password):
        """Create Super User"""
        user = self.create_user(
            email,
            password=password
        )
        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser, PermissionsMixin):
    """User Model"""
    email = models.EmailField(max_length=255, unique=True, db_index=True)

    USERNAME_FIELD = 'email'
    name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    adress = models.CharField(max_length=50)
    zip_Code = models.IntegerField()
    city = models.CharField(max_length=50)
    phone_number = models.CharField(max_length=20)

    objects = CustomUserManager()

    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        self.email = self.email.lower()
        super(User, self).save(*args, **kwargs)


class Product(models.Model):
    """Model For Product"""
    name = models.CharField(max_length=50)
    price = models.DecimalField(max_digits=5, decimal_places=2)
    quantity = models.IntegerField()
    description = models.CharField(max_length=200)
    date = models.DateTimeField(auto_now_add=True)
    seller = models.ForeignKey(User)
    is_active = models.BooleanField(default=True)
    picture = models.ImageField(upload_to='KmetApp/Media/', null=True, blank=True)
    origin = models.CharField(max_length=50)


class Order_Product(models.Model):
    """Orders for Product"""
    price_order = models.DecimalField(max_length=10, max_digits=5,
                                      decimal_places=2)
    quantity_order = models.IntegerField()
    is_completed = models.BooleanField(default=False)
    date_submission = models.DateTimeField(auto_now_add=True)
    date_completed = models.DateTimeField(null=True)
    product = models.ForeignKey(Product)
    buyer = models.ForeignKey(User)


class Basket(models.Model):
    """Model for Basket """
    name = models.CharField(max_length=50)
    price = models.DecimalField(max_length=10, max_digits=5, decimal_places=2)
    quantity = models.IntegerField()
    total_amount = models.IntegerField()
    description = models.CharField(max_length=200)
    seller = models.ForeignKey(User)
    date = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True)
    picture = models.ImageField(upload_to='KmetApp/Media/', null=True)
    origin = models.CharField(max_length=50)


class Order_Basket(models.Model):
    """Model for Basket """
    price_order = models.DecimalField(max_length=10, max_digits=5, decimal_places=2)
    quantity_order = models.IntegerField()
    date_submission = models.DateTimeField(auto_now_add=True)
    date_completed = models.DateTimeField(blank=True)
    frequency = models.CharField(max_length=40)
    is_completed = models.BooleanField(default=False)
    basket = models.ForeignKey(Basket)
    buyer = models.ForeignKey(User)


class News(models.Model):
    tittle = models.CharField(max_length = 100, blank=True)
    description = models.CharField(max_length = 50000, blank=True)
    post_date = models.DateTimeField(default= None, blank= True)



class Attachments(models.Model):
    picture = models.ImageField(upload_to='KmetApp/Media',null=True, blank=True)
    news = models.ForeignKey(News)

KmetApp/forms.py
from django import forms
from KmetApp.models import User, Product, Basket
from django.contrib.auth.forms import UserCreationForm


class UserForm(UserCreationForm):
    """User Form"""
    class Meta:
        """Class Meta defined"""
        model = User
        exclude = ['password', 'is_active']

    def save(self, commit=True):
        """Save method"""
        user = super(UserForm, self).save(commit=False)

        if commit:
            user.save()
        return user


class ProductForm(forms.ModelForm):
    """Add Selling Form"""
    class Meta:
        model = Product
        exclude = ['is_active', 'seller']

    def save(self, commit=True):
        """Save Method"""
        selling = super(ProductForm, self).save(commit=False)

        if commit:
            selling.save()
        return selling


class UserEditForm(forms.ModelForm):
    """User Edit Form"""
    class Meta:
        model = User
        exclude = ['password', 'is_active', 'email', 'password1', 'password2']

    def save(self, commit=True):
        """Save Method"""
        user = super(UserEditForm, self).save(commit=False)

        if commit:
            user.save()
        return user


class BasketForm(forms.ModelForm):
    """Add Basket Form"""
    class Meta:
        model = Basket
        exclude = ['is_active', 'seller']

    def save(self, commit=True):
        """Save Method"""
        basket = super(BasketForm, self).save(commit=False)

        if commit:
            basket.save()
        return basket

KmetApp/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from KmetApp.models import User, Product, Basket, Order_Product, Order_Basket
import datetime
from django.shortcuts import redirect
from KmetApp.forms import UserForm, UserEditForm, ProductForm, BasketForm
from django.views.decorators.csrf import csrf_exempt

# Create your views here.


def home(request):
    """Return Index HTML"""
    return render(request, 'index.html')


def loginview(request):
    """Return LogIn HTML"""
    return render(request, 'User/LogIn.html')


def register_user(request):
    """Registration User Handler"""
    form = UserForm()
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('KmetApp:home')
        else:
            return render(request, 'User/Registration.html', {'form': form})
    else:
        return render(request, 'User/Registration.html')


def logon(request):
    """Log In User Handler"""
    if request.method == 'POST':
        username = request.POST['email']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('KmetApp:home')
        else:
            return render(request, 'User/LogIn.html', {'user': username})
    return render(request, 'User/LogIn.html')


def logoff(request):
    """Log out user"""
    logout(request)
    return redirect('KmetApp:home')


def add_selling(request):
    """Add Selling"""
    form = ProductForm()
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            bbb = form.save(commit=False)
            seller = User.objects.get(id=request.user.id)
            bbb.seller = seller
            bbb.save()
            return render(request, 'Sellings/Selling.html')
        else:
            return render(request, 'Sellings/Add_Selling.html', {'form': form})
    else:
        return render(request, 'Sellings/Add_Selling.html')


def edit_user(request):
    """"Edit User"""
    form = UserEditForm()
    if request.method == 'POST':
        form = UserEditForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('KmetApp:home')
        else:
            return render(request, 'User/Edit.html', {'form': form})
    else:
        return render(request, 'User/Edit.html')


@csrf_exempt
def search_selling(request):
    """Search Sellings in database"""
    if request.method == 'POST':
        search_term = request.POST['search_term']
        if request.user.is_authenticated():
            user = User.objects.get(id=request.user.id)
            sellings = Selling.objects.filter(name__icontains=search_term).exclude(quantity=0).exclude(seller=user).exclude(is_Active=False)
            return render(request, 'Sellings/Selling.html', {'sellings': sellings})
        else:
            sellings = Selling.objects.filter(name__icontains=search_term).exclude(quantity=0).exclude(is_Active=False)
            return render(request, 'Sellings/Selling.html', {'sellings': sellings})
    else:
        return render(request, 'Sellings/Selling.html')


def add_orderS(request):
    """Add order for Selling"""
    if request.method == 'POST':
        quantity = int(request.POST['quantity'])
        selling = Selling.objects.get(id=request.POST['selling'])
        user = User.objects.get(id=request.user.id)
        if(selling.quantity-quantity >= 0):
            selling.quantity = selling.quantity - quantity
            selling.save()
            order = Order_Selling.objects.create(price_Order=selling.price*quantity, quantity_Order=quantity,
            selling=selling, buyer=user)
        else:
            return redirect('KmetApp:search_selling')
        return redirect('KmetApp:search_selling')


def my_sellings(request):
    """View for Users Sellings"""
    user = User.objects.get(id=request.user.id)
    sellings = Selling.objects.filter(seller=user).exclude(is_Active=False)
    return render(request, 'Sellings/MySellings.html', {'sellings': sellings})


def disable_selling(request):
    """Function to disable an active selling"""
    selling = request.GET.get('id')
    disable = Selling.objects.get(id=selling)
    if(disable.seller.id == request.user.id):
        disable.is_Active = False
        disable.save()
    return redirect('KmetApp:my_sellings')


def add_basket(request):
    """Add Basket"""
    form = BasketForm()
    if request.method == 'POST':
        form = BasketForm(request.POST, request.FILES)
        if form.is_valid():
            bbb = form.save(commit=False)
            seller = User.objects.get(id=request.user.id)
            bbb.seller = seller
            bbb.save()
            return render(request, 'Basket/Basket.html')
        else:
            return render(request, 'Basket/Add_Basket.html', {'form': form})
    else:
        return render(request, 'Basket/Add_Basket.html')


@csrf_exempt
def search_basket(request):
    """Search Basket in database"""
    if request.method == 'POST':
        search_term = request.POST['search_term']
        if request.user.is_authenticated():
            user = User.objects.get(id=request.user.id)
            baskets = Basket.objects.filter(name__icontains=search_term).exclude(quantity=0).exclude(seller=user).exclude(is_Active=False).exclude(total_Amount=0)
            return render(request, 'Basket/Basket.html', {'baskets': baskets})
        else:
            baskets = Basket.objects.filter(name__icontains=search_term).exclude(quantity=0).exclude(is_Active=False).exclude(total_Amount=0)
            return render(request, 'Basket/Basket.html', {'baskets': baskets})
    else:
        return render(request, 'Basket/Basket.html')


def my_OrderSellings(request):
    """Returns the view with all submited Orders"""
    user = User.objects.get(id=request.user.id)
    orders = Order_Selling.objects.filter(buyer=user)
    return render(request, 'OrderSellings/MyOrders.html', {'orders': orders})


def undoneOrder(request):
    """"Display All undone Orders for a Selling"""
    user = User.objects.get(id=request.user.id)
    orders = Order_Selling.objects.filter(selling__seller=user, is_Completed=False)
    return render(request, 'OrderSellings/UnCompletedOrders.html', {'orders': orders})


def doneOrder(request):
    """"Display All done Orders for a Selling"""
    user = User.objects.get(id=request.user.id)
    orders = Order_Selling.objects.filter(selling__seller=user, is_Completed=True)
    return render(request, 'OrderSellings/CompletedOrders.html', {'orders': orders})


def editSelling(request):
    """"Action where you can edit an active selling"""
    if request.method == 'POST':
        selling = Selling.objects.get(id=request.POST['selling'])
        if(selling.seller.id == request.user.id):
            selling.name = request.POST['name']
            selling.price = request.POST.get('price', False)
            selling.description = request.POST['description']
            selling.origin = request.POST['origin']
            selling.quantity = request.POST['quantity']
            if(request.POST['picture']):
                selling.picture = request.POST['picture']
            selling.save()
    return redirect('KmetApp:my_sellings')


def complete_orderSelling(request):
    """Function to complete an active order"""
    id = request.GET.get('id')
    user = User.objects.get(id=request.user.id)
    order = Order_Selling.objects.get(id=id, selling__seller=user)
    if(order):
        order.is_Completed = True
        order.date_Completed = datetime.now()
        order.save()
    return redirect('KmetApp:undoneOrder')


def add_orderB(request):
    """Add order for Selling"""
    if request.method == 'POST':
        quantity = int(request.POST['quantity'])
        frequency = int(request.POST['frequency'])
        basket = Basket.objects.get(id=request.POST['basket'])
        user = User.objects.get(id=request.user.id)
        if(basket.quantity-quantity >= 0):
            basket.quantity = basket.quantity - quantity
            basket.frequency = frequency
            basket.save()
            order = Order_Basket.objects.create(price_Order=basket.price*quantity, quantity_Order=quantity, frequency=frequency,
            basket=basket, buyer=user)
        else:
            return redirect('KmetApp:search_basket')
        return redirect('KmetApp:search_basket')


def disable_basket(request):
    """Function to disable an active basket"""
    basket = request.GET.get('id')
    disable = Basket.objects.get(id=basket)
    if(disable.seller.id == request.user.id):
        disable.is_Active = False
        disable.save()
    return redirect('KmetApp:my_sellings')


def my_baskets(request):
    """View for Users Baskets"""
    user = User.objects.get(id=request.user.id)
    baskets = Basket.objects.filter(seller=user).exclude(is_Active=False)
    return render(request, 'Basket/MyBasket.html', {'baskets': baskets})


def editBasket(request):
    """"Action where you can edit an active selling"""
    if request.method == 'POST':
        basket = Basket.objects.get(id=request.POST['basket'])
        if(basket.seller.id == request.user.id):
            basket.name = request.POST['name']
            basket.price = request.POST.get('price', False)
            basket.total_Amount = request.POST.get('total_Amount', False)
            basket.description = request.POST['description']
            basket.origin = request.POST['origin']
            basket.quantity = request.POST['quantity']
            if(request.POST['picture']):
                basket.picture = request.POST['picture']
            basket.save()
    return redirect('KmetApp:my_baskets')


def my_OrderBasket(request):
    """Returns the view with all submited Orders"""

KmetApp/templates/Sellings/Add_Selling.html
{% extends '__base__.html' %} {% block content %}

<div class="col-md-12">
                <form method="POST" action="{% url 'KmetApp:add_selling' %}" enctype="multipart/form-data">
                {% csrf_token %}
		        <div class="col-md-12 form-group">        
                    <label  class="control-label col-md-3">Ime oglasa</label>
                        <div class="col-md-6">
                        <input type="text" name="name" id="ime_O" value="{{form.name.value}}" placeholder="Ime izdelka" class="form-control">
                    </div>
                    </div>
                    <div class="col-md-12 form-group">
                        <label class="control-label col-md-3">Cena izdelka</label>
                        <div class="col-md-6">
                        <input type="text" name="price" placeholder="Cena izdelka" value="{{form.price.value}}" class="form-control">
                        </div>
                    </div>
                    <div class="col-md-12 form-group">
                        <label class="control-label col-md-3">Količina izdelka</label>
                        <div class="col-md-6">
                        <input type="number" name="quantity" placeholder="Količina Izdelka" value="{{form.quantity.value}}" class="form-control">
                    </div>
                    </div>
                    <div class="col-md-12 form-group">
                        <label class="control-label col-md-3">Mesto pridelave</label>
                        <div class="col-md-6">
                        <input type="text" name="origin" placeholder="Mesto Pridelave" value="{{form.origin.value}}" class="form-control">
                    </div>
                    </div>
                    <div class="col-md-12 form-group">
                        <label class="control-label col-md-3">Opis izdelka</label>
                        <div class="col-md-6">
                        <textarea name="description" placeholder="Opis Izdelka" value="{{form.description.value}}" class="form-control" rows="2ddddddd"></textarea>
                    </div>
                    </div>
                    <div class="col-md-12 form-group">
                        <input id="slika" type="file" name="picture" value="{{form.picture.value}}">
                    </div>
                    <br>
                    <button type="submit" class="btn btn btn-info col-md-offset-3">Oddaj Oglas</button>
                    <br>
                </div>
        </div>
        {% csrf_token %}
        </form>
    </div>
{% endblock %}

KmetApp/templates/Sellings/MySellings.html
{% extends '__base__.html' %} {% load staticfiles %} {% csrf_token %} {% block hdr %}

<header class="intro-header" style="background-image: url({% static 'img/prijava-bg.jpg' %})">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">

        <div class="page-heading">
          <h1>Moji oglasi</h1>
          <hr class="small">
          <span class="subheading">Spisek vaših oglasov</span>
        </div>
      </div>
    </div>
  </div>
</header>
{% endblock %} {% block content %} {% for selling in sellings %}
<div class="container">

  <div class="item col-md-12 col-md-offset-3">
    {% if selling.picture %}
    <img src="{{selling.picture}}" width="250" height="250"></img>
    {%else %}
    <img src="{% static 'img/Selling/default.jpg' %}" width="250" height="250"></img>
    {% endif %}
    <h3 class="name"><a ng-href="#">{{ selling.name }} </a>
      <div class="item col-md-12 col-md-offset-3">
    </h3>
    <ul>
      <li class="price" name="cena_O"> Cena izdelka: {{ selling.price }} €/kg</li>
      <li class="quantity" name="kolicina_O"> Kolicina: {{ selling.quantity }} kg </li>
      <li class="mesto_pridelave"> Mesto pridelave: {{selling.origin}}</li>
      <li class="description"> Opis: {{ selling.description }} </li>

    </ul>
    <a class="btn btn-lg btn-info model" id="submit1" href="#" style="
                    font-size: 12px;
                    padding: 5px 2px;" data-toggle="modal" data-target="#myModal" data-selling='{"id":{{selling.id}}, "name":"{{selling.name}}", "price":"{{selling.price}}",
               "quantity":"{{selling.quantity}}","origin":"{{selling.origin}}", 
               "description":"{{selling.description}}"}'>Popravek Oglasa </a>

    <a class="btn btn-lg btn-info" style="
                font-size: 12px;
                padding: 5px 2px;" href="{% url 'KmetApp:disable_selling' %}?id={{selling.id}}">Zaključek oglasa</a>    <br /><br /><br /><br />
    </div>
  </div>
  {% endfor %}


  <div class="modal fade" tabindex="-1" role="dialog" id="myModal">
    <form action="{% url 'KmetApp:editSelling' %}" method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title">Popravek oglasa</h4>
          </div>
          <div class="modal-body">
            <ul>
              <li>Ime oglasa: <input type="text" name="name" value="" id="name"></li>
              <li>Cena izdelka: <input type="text" name="price" id="price" value="">€/kg</li>
              <li>Količina izdelka: <input type="integer" name="quantity" value="" id="quantity"></li>
              <li>Mesto Pridelave: <input type="text" value="" name="origin" id="origin"></li>
              <li>Opis: <input type="text" name="description" value="" id="description"></li>
              <div class="form-group">
                <li><input type="file" value="" name="picture" id="picture"></li>
                <input type="hidden" type="text" value="" name="selling" id="selling">
            </ul>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
              <input type="submit" class="btn btn-primary">

            </div>
          </div>
          <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </form>
    </div>
    <!-- /.modal -->

    <script src="{% static 'js/jquery2.2.4.js' %}"></script>
    <script Content-Type="javascript">
      $('.model').on('click', function (e) {
        let data = $(this).data('selling');
        $(".modal-body #selling").val(data.id);
        $(".modal-body #name").val(data.name);
        $(".modal-body #description").val(data.description);
        $(".modal-body #price").val(data.price);
        $(".modal-body #quantity").val(data.quantity);
        $(".modal-body #origin").val(data.origin);
      });

    </script>
    {% endblock %}

KmetApp/templates/Sellings/Selling.html
{% extends '__base__.html' %} {% load staticfiles %} {% block hdr %}

<header class="intro-header" style="background-image: url({% static 'img/prijava-bg.jpg' %})">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">

                <div class="page-heading">
                    <h1>Iskanje Oglasov</h1>
                    <hr class="small">
                    <span class="subheading">Tukaj lahko vsak poišče registriran oglas.</span>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %} {% block content %}
<form class="form-wrapper" method="POST" action="{% url 'KmetApp:search_selling' %}">
    <div class="form-group col-md-9">
        <input type="text" name="search_term" class="form-control" placeholder="Iskanje oglasov">
    </div>
    <input type="submit" id="submit">
</form>

{% for selling in sellings %}
<div class="container" style="padding-left: 200px">
    {% if selling.picture %}
    <img src="{{selling.picture}}" width="250" height="250"></img>
    {%else %}
    <img src="{% static 'img/Selling/default.jpg' %}" {% endif %} <h3 class="name"><a>{{ selling.name }} </a>
    <div class="item col-md-12 col-md-offset-3">
        </h3>
        <ul>
            <li class="price" name="cena_O"> Cena izdelka: {{ selling.price }} €/kg</li>
            <li class="quantity" name="kolicina_O"> Kolicina: {{ selling.quantity }} kg </li>
            <li class="prodajalec"> Ime prodajalca: {{selling.seller.name}}</li>
            <li class="mesto_pridelave"> Mesto pridelave: {{selling.origin}}</li>
            <li class="description"> Opis: {{ selling.description }} </li>
        </ul>
        {%if request.user.is_authenticated %}
        <a class="btn btn-lg btn-info model" href="#" style="
                font-size: 12px;
                padding: 5px 2px;" data-toggle="modal" data-target="#myModal" data-id="{{selling.id}}">Oddaja naročila </a>        {% endif %}
        <br></br>

    </div>
</div>

</div>
{% endfor %}

<div class="modal fade" tabindex="-1" role="dialog" id="myModal">
    <form action="{% url 'KmetApp:add_orderS' %}" method="POST">
        {% csrf_token %}
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">Oddaja naročila</h4>
                </div>
                <div class="modal-body">
                    Količina izdelka: <input type="integer" name="quantity" id="kolicina" value="">
                    <input type="hidden" type="text" value="" name="selling" id="selling">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <input type="submit" class="btn btn-primary" data-dismiss="modal">
                </div>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </form>
</div>
<!-- /.modal -->
<script src="https://code.jquery.com/jquery-2.2.4.js" integrity="sha256-iT6Q9iMJYuQiMWNd9lDyBUStIq/8PuOW33aOqmvFpqI=" crossorigin="anonymous"></script>
<script>
    $('.model').on('click', function (e) {
        var sellingId = $(this).data('id');
        $(".modal-body #selling").val(sellingId);
    });

</script>

{% endblock %}