KmetApp/urls.py
from django.conf.urls import url

from . import views


app_name = 'KmetApp'

urlpatterns = [
    url(r'^home/', views.home, name='home'),
    url(r'^register_user/', views.register_user, name='register_user'),
    url(r'^logon/', views.logon, name='logon'),
    url(r'^logoff/', views.logoff, name='logoff'),
    url(r'^add_selling/', views.add_selling, name='add_selling'),
    url(r'^edit_user/', views.edit_user, name='edit_user'),
    url(r'^search_selling/', views.search_selling, name='search_selling'),
    url(r'^add_orderS/', views.add_orderS, name='add_orderS'),
    url(r'^my_sellings/', views.my_sellings, name='my_sellings'),
    url(r'^disable_selling/', views.disable_selling, name='disable_selling'),
    url(r'^add_basket/', views.add_basket, name='add_basket'),
    url(r'^search_basket/', views.search_basket, name='search_basket'),
    url(r'^my_OrderSellings/', views.my_OrderSellings, name='my_OrderSellings'),
    url(r'^undoneOrder/', views.undoneOrder, name='undoneOrder'),
    url(r'^doneOrder/', views.doneOrder, name='doneOrder'),
    url(r'^editSelling/', views.editSelling, name='editSelling'),
    url(r'^complete_orderSelling/', views.complete_orderSelling, name='complete_orderSelling'),
    url(r'^add_orderB/', views.add_orderB, name='add_orderB'),
    url(r'^disable_basket/', views.disable_basket, name='disable_basket'),
    url(r'^my_baskets/', views.my_baskets, name='my_baskets'),
    url(r'^editBasket/', views.editBasket, name='editBasket'),
    url(r'^my_OrderBasket/', views.my_OrderBasket, name='my_OrderBasket'),
    url(r'^undoneOrderB/', views.undoneOrderB, name='undoneOrderB'),
    url(r'^doneOrderB/', views.doneOrderB, name='doneOrderB'),
    url(r'^complete_orderBasket/', views.complete_orderBasket, name='complete_orderBasket'),
    


]

KmetSite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^app/', include('KmetApp.urls', namespace="KmetApp"))
]

KmetApp/models.py
from django.db import models
from django.contrib.auth.models import (BaseUserManager, AbstractBaseUser,
                                        PermissionsMixin)


class CustomUserManager(BaseUserManager):
    """ Custom Manager """
    def create_user(self, email, password=None):
        """ create user method"""
        if not email:
            raise ValueError("User more imet email!")

        email = email.lower()
        user = self.model(email=CustomUserManager.normalize_email(email))
        user.set_password(password)
        user.save(using=self._db)
        user.is_staff = False
        user.is_admin = False
        user.is_active = True
        return user

    def create_superuser(self, email, password):
        """Create Super User"""
        user = self.create_user(
            email,
            password=password
        )
        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser, PermissionsMixin):
    """User Model"""
    email = models.EmailField(max_length=255, unique=True, db_index=True)

    USERNAME_FIELD = 'email'
    name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    adress = models.CharField(max_length=50)
    zip_Code = models.IntegerField()
    city = models.CharField(max_length=50)
    phone_number = models.CharField(max_length=20)

    objects = CustomUserManager()

    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        self.email = self.email.lower()
        super(User, self).save(*args, **kwargs)


class Product(models.Model):
    """Model For Product"""
    name = models.CharField(max_length=50)
    price = models.DecimalField(max_digits=5, decimal_places=2)
    quantity = models.IntegerField()
    description = models.CharField(max_length=200)
    date = models.DateTimeField(auto_now_add=True)
    seller = models.ForeignKey(User)
    is_active = models.BooleanField(default=True)
    picture = models.ImageField(upload_to='KmetApp/Media/', null=True, blank=True)
    origin = models.CharField(max_length=50)


class Order_Product(models.Model):
    """Orders for Product"""
    price_order = models.DecimalField(max_length=10, max_digits=5,
                                      decimal_places=2)
    quantity_order = models.IntegerField()
    is_completed = models.BooleanField(default=False)
    date_submission = models.DateTimeField(auto_now_add=True)
    date_completed = models.DateTimeField(null=True)
    product = models.ForeignKey(Product)
    buyer = models.ForeignKey(User)


class Basket(models.Model):
    """Model for Basket """
    name = models.CharField(max_length=50)
    price = models.DecimalField(max_length=10, max_digits=5, decimal_places=2)
    quantity = models.IntegerField()
    total_amount = models.IntegerField()
    description = models.CharField(max_length=200)
    seller = models.ForeignKey(User)
    date = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True)
    picture = models.ImageField(upload_to='KmetApp/Media/', null=True)
    origin = models.CharField(max_length=50)


class Order_Basket(models.Model):
    """Model for Basket """
    price_order = models.DecimalField(max_length=10, max_digits=5, decimal_places=2)
    quantity_order = models.IntegerField()
    date_submission = models.DateTimeField(auto_now_add=True)
    date_completed = models.DateTimeField(blank=True)
    frequency = models.CharField(max_length=40)
    is_completed = models.BooleanField(default=False)
    basket = models.ForeignKey(Basket)
    buyer = models.ForeignKey(User)


class News(models.Model):
    tittle = models.CharField(max_length = 100, blank=True)
    description = models.CharField(max_length = 50000, blank=True)
    post_date = models.DateTimeField(default= None, blank= True)



class Attachments(models.Model):
    picture = models.ImageField(upload_to='KmetApp/Media',null=True, blank=True)
    news = models.ForeignKey(News)

KmetApp/forms.py
from django import forms
from KmetApp.models import User, Product, Basket
from django.contrib.auth.forms import UserCreationForm


class UserForm(UserCreationForm):
    """User Form"""
    class Meta:
        """Class Meta defined"""
        model = User
        exclude = ['password', 'is_active']

    def save(self, commit=True):
        """Save method"""
        user = super(UserForm, self).save(commit=False)

        if commit:
            user.save()
        return user


class ProductForm(forms.ModelForm):
    """Add Selling Form"""
    class Meta:
        model = Product
        exclude = ['is_active', 'seller']

    def save(self, commit=True):
        """Save Method"""
        selling = super(ProductForm, self).save(commit=False)

        if commit:
            selling.save()
        return selling


class UserEditForm(forms.ModelForm):
    """User Edit Form"""
    class Meta:
        model = User
        exclude = ['password', 'is_active', 'email', 'password1', 'password2']

    def save(self, commit=True):
        """Save Method"""
        user = super(UserEditForm, self).save(commit=False)

        if commit:
            user.save()
        return user


class BasketForm(forms.ModelForm):
    """Add Basket Form"""
    class Meta:
        model = Basket
        exclude = ['is_active', 'seller']

    def save(self, commit=True):
        """Save Method"""
        basket = super(BasketForm, self).save(commit=False)

        if commit:
            basket.save()
        return basket

KmetApp/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from KmetApp.models import User, Product, Basket, Order_Product, Order_Basket
import datetime
from django.shortcuts import redirect
from KmetApp.forms import UserForm, UserEditForm, ProductForm, BasketForm
from django.views.decorators.csrf import csrf_exempt

# Create your views here.


def home(request):
    """Return Index HTML"""
    return render(request, 'index.html')


def loginview(request):
    """Return LogIn HTML"""
    return render(request, 'User/LogIn.html')


def register_user(request):
    """Registration User Handler"""
    form = UserForm()
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('KmetApp:home')
        else:
            return render(request, 'User/Registration.html', {'form': form})
    else:
        return render(request, 'User/Registration.html')


def logon(request):
    """Log In User Handler"""
    if request.method == 'POST':
        username = request.POST['email']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('KmetApp:home')
        else:
            return render(request, 'User/LogIn.html', {'user': username})
    return render(request, 'User/LogIn.html')


def logoff(request):
    """Log out user"""
    logout(request)
    return redirect('KmetApp:home')


def add_selling(request):
    """Add Selling"""
    form = ProductForm()
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            bbb = form.save(commit=False)
            seller = User.objects.get(id=request.user.id)
            bbb.seller = seller
            bbb.save()
            return render(request, 'Sellings/Selling.html')
        else:
            return render(request, 'Sellings/Add_Selling.html', {'form': form})
    else:
        return render(request, 'Sellings/Add_Selling.html')


def edit_user(request):
    """"Edit User"""
    form = UserEditForm()
    if request.method == 'POST':
        form = UserEditForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('KmetApp:home')
        else:
            return render(request, 'User/Edit.html', {'form': form})
    else:
        return render(request, 'User/Edit.html')


@csrf_exempt
def search_selling(request):
    """Search Sellings in database"""
    if request.method == 'POST':
        search_term = request.POST['search_term']
        if request.user.is_authenticated():
            user = User.objects.get(id=request.user.id)
            sellings = Selling.objects.filter(name__icontains=search_term).exclude(quantity=0).exclude(seller=user).exclude(is_Active=False)
            return render(request, 'Sellings/Selling.html', {'sellings': sellings})
        else:
            sellings = Selling.objects.filter(name__icontains=search_term).exclude(quantity=0).exclude(is_Active=False)
            return render(request, 'Sellings/Selling.html', {'sellings': sellings})
    else:
        return render(request, 'Sellings/Selling.html')


def add_orderS(request):
    """Add order for Selling"""
    if request.method == 'POST':
        quantity = int(request.POST['quantity'])
        selling = Selling.objects.get(id=request.POST['selling'])
        user = User.objects.get(id=request.user.id)
        if(selling.quantity-quantity >= 0):
            selling.quantity = selling.quantity - quantity
            selling.save()
            order = Order_Selling.objects.create(price_Order=selling.price*quantity, quantity_Order=quantity,
            selling=selling, buyer=user)
        else:
            return redirect('KmetApp:search_selling')
        return redirect('KmetApp:search_selling')


def my_sellings(request):
    """View for Users Sellings"""
    user = User.objects.get(id=request.user.id)
    sellings = Selling.objects.filter(seller=user).exclude(is_Active=False)
    return render(request, 'Sellings/MySellings.html', {'sellings': sellings})


def disable_selling(request):
    """Function to disable an active selling"""
    selling = request.GET.get('id')
    disable = Selling.objects.get(id=selling)
    if(disable.seller.id == request.user.id):
        disable.is_Active = False
        disable.save()
    return redirect('KmetApp:my_sellings')


def add_basket(request):
    """Add Basket"""
    form = BasketForm()
    if request.method == 'POST':
        form = BasketForm(request.POST, request.FILES)
        if form.is_valid():
            bbb = form.save(commit=False)
            seller = User.objects.get(id=request.user.id)
            bbb.seller = seller
            bbb.save()
            return render(request, 'Basket/Basket.html')
        else:
            return render(request, 'Basket/Add_Basket.html', {'form': form})
    else:
        return render(request, 'Basket/Add_Basket.html')


@csrf_exempt
def search_basket(request):
    """Search Basket in database"""
    if request.method == 'POST':
        search_term = request.POST['search_term']
        if request.user.is_authenticated():
            user = User.objects.get(id=request.user.id)
            baskets = Basket.objects.filter(name__icontains=search_term).exclude(quantity=0).exclude(seller=user).exclude(is_Active=False).exclude(total_Amount=0)
            return render(request, 'Basket/Basket.html', {'baskets': baskets})
        else:
            baskets = Basket.objects.filter(name__icontains=search_term).exclude(quantity=0).exclude(is_Active=False).exclude(total_Amount=0)
            return render(request, 'Basket/Basket.html', {'baskets': baskets})
    else:
        return render(request, 'Basket/Basket.html')


def my_OrderSellings(request):
    """Returns the view with all submited Orders"""
    user = User.objects.get(id=request.user.id)
    orders = Order_Selling.objects.filter(buyer=user)
    return render(request, 'OrderSellings/MyOrders.html', {'orders': orders})


def undoneOrder(request):
    """"Display All undone Orders for a Selling"""
    user = User.objects.get(id=request.user.id)
    orders = Order_Selling.objects.filter(selling__seller=user, is_Completed=False)
    return render(request, 'OrderSellings/UnCompletedOrders.html', {'orders': orders})


def doneOrder(request):
    """"Display All done Orders for a Selling"""
    user = User.objects.get(id=request.user.id)
    orders = Order_Selling.objects.filter(selling__seller=user, is_Completed=True)
    return render(request, 'OrderSellings/CompletedOrders.html', {'orders': orders})


def editSelling(request):
    """"Action where you can edit an active selling"""
    if request.method == 'POST':
        selling = Selling.objects.get(id=request.POST['selling'])
        if(selling.seller.id == request.user.id):
            selling.name = request.POST['name']
            selling.price = request.POST.get('price', False)
            selling.description = request.POST['description']
            selling.origin = request.POST['origin']
            selling.quantity = request.POST['quantity']
            if(request.POST['picture']):
                selling.picture = request.POST['picture']
            selling.save()
    return redirect('KmetApp:my_sellings')


def complete_orderSelling(request):
    """Function to complete an active order"""
    id = request.GET.get('id')
    user = User.objects.get(id=request.user.id)
    order = Order_Selling.objects.get(id=id, selling__seller=user)
    if(order):
        order.is_Completed = True
        order.date_Completed = datetime.now()
        order.save()
    return redirect('KmetApp:undoneOrder')


def add_orderB(request):
    """Add order for Selling"""
    if request.method == 'POST':
        quantity = int(request.POST['quantity'])
        frequency = int(request.POST['frequency'])
        basket = Basket.objects.get(id=request.POST['basket'])
        user = User.objects.get(id=request.user.id)
        if(basket.quantity-quantity >= 0):
            basket.quantity = basket.quantity - quantity
            basket.frequency = frequency
            basket.save()
            order = Order_Basket.objects.create(price_Order=basket.price*quantity, quantity_Order=quantity, frequency=frequency,
            basket=basket, buyer=user)
        else:
            return redirect('KmetApp:search_basket')
        return redirect('KmetApp:search_basket')


def disable_basket(request):
    """Function to disable an active basket"""
    basket = request.GET.get('id')
    disable = Basket.objects.get(id=basket)
    if(disable.seller.id == request.user.id):
        disable.is_Active = False
        disable.save()
    return redirect('KmetApp:my_sellings')


def my_baskets(request):
    """View for Users Baskets"""
    user = User.objects.get(id=request.user.id)
    baskets = Basket.objects.filter(seller=user).exclude(is_Active=False)
    return render(request, 'Basket/MyBasket.html', {'baskets': baskets})


def editBasket(request):
    """"Action where you can edit an active selling"""
    if request.method == 'POST':
        basket = Basket.objects.get(id=request.POST['basket'])
        if(basket.seller.id == request.user.id):
            basket.name = request.POST['name']
            basket.price = request.POST.get('price', False)
            basket.total_Amount = request.POST.get('total_Amount', False)
            basket.description = request.POST['description']
            basket.origin = request.POST['origin']
            basket.quantity = request.POST['quantity']
            if(request.POST['picture']):
                basket.picture = request.POST['picture']
            basket.save()
    return redirect('KmetApp:my_baskets')


def my_OrderBasket(request):
    """Returns the view with all submited Orders"""

KmetApp/templates/__base__.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="slo">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Veseli Kmet</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'css/clean-blog.min.css' %}" rel="stylesheet">


    <link href="{% static 'css/img.css' %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href='https://fonts.googleapis.com/css?family=Playfair+Display:400,400italic,700italic|Oswald' rel='stylesheet' type='text/css'>
    <link href="{% static 'css/main.css' %}" rel="stylesheet" />
    <style>

    </style>
</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-custom navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header ">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"
                    aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li class="nav-item"> <a style="background-color: transparent;
                            color: black;
                            padding: 16px;
                            font-size: 14px;
                            border: none;
                            cursor: pointer;
                            text-transform: none;
                            font-weight: 400;" class="nav-link" href="{% url 'KmetApp:home' %}">Domov</a>
                        {% if user.is_authenticated %}
                            <li class="nav-item">
                                <a style= "background-color: transparent;
                            color: black;
                            padding: 16px;
                            font-size: 14px;
                            border: none;
                            cursor: pointer;
                            text-transform: none;
                            font-weight: 400;" class="nav-link" href="{% url 'KmetApp:edit_user' %}">Urejanje Profila</a> 
                            </li>
                        {% endif %}
                        <li class="nav-item dropdown">
                                <button class="dropbtn" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Oglasi</button>
                                <div class="dropdown-content">
                                    <a class="nav-link" href="{% url 'KmetApp:search_selling' %}">Iskanje oglasov</a>
                                    {% if user.is_authenticated %}
                                        <a class="nav-link" href="{% url 'KmetApp:add_selling' %}">Oddaja oglasa</a>
                                        <a class="nav-link" href="{% url 'KmetApp:my_sellings' %}">Moji oglasi </a>
                                    {% endif %}
                                </div>
                        </li>
                        {% if user.is_authenticated %}
                        <li class="dropdown">
                            <button class="dropbtn" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Narocila za oglase</button>
                            <div class="dropdown-content">
                                   <a href="{% url 'KmetApp:undoneOrder' %}">Neobdelana Narocila</a>
                                   <a href="{% url 'KmetApp:my_OrderSellings' %}">Moja naročila</a>
                                   <a href="{% url 'KmetApp:doneOrder' %}">Obdelana naročila</a>
                            </div>
                            </li>
                            {% endif %}

                            <li class="dropdown">
                                <button class="dropbtn" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Kosarica</button>
                                <div class="dropdown-content">
                                        <a class="nav-link" href="{% url 'KmetApp:search_basket' %}">Iskanje Košaric</a> 
                                        {% if user.is_authenticated %}
                                            <a class="nav-link" href="{% url 'KmetApp:add_basket' %}">Oddaja oglasa</a>
                                            <a class="nav-link"href="{% url 'KmetApp:my_baskets' %}"> Moji Košarice </a> 
                                        {% endif %}
                                </div>
                                </li>

                                {% if user.is_authenticated %}
                                <li class="dropdown">
                                    <button class="dropbtn" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Narocila za Kosarico</button>
                                    <div class="dropdown-content">
                                            <a class="nav-link" href="{% url 'KmetApp:undoneOrderB' %}">Neobdelana Narocila</a>
                                            <a class="nav-link" href="{% url 'KmetApp:my_OrderBasket' %}">Moja naročila</a>
                                            <a class="nav-link" href="{% url 'KmetApp:doneOrderB' %}">Obdelana naročila</a>
                                    </div>
                                </li>
                                {% endif %}
                </ul>
                <ul class="nav navbar-nav navbar-left">

                    {% if user.is_authenticated %}
                    <li>
                        <a style="background-color: transparent;
                            color: black;
                            padding: 16px;
                            font-size: 14px;
                            border: none;
                            cursor: pointer;
                            text-transform: none;
                            font-weight: 400;" href="{% url 'KmetApp:logoff' %}"> LogOut</a> {% else %}
                        <li>
                            <a style="background-color: transparent;
                            color: black;
                            padding: 16px;
                            font-size: 14px;
                            border: none;
                            cursor: pointer;
                            text-transform: none;
                            font-weight: 400;" href="{% url 'KmetApp:logon' %}">Prijava </a>

                            <li>
                                <a style="background-color: transparent;
                            color: black;
                            padding: 16px;
                            font-size: 14px;
                            border: none;
                            cursor: pointer;
                            text-transform: none;
                            font-weight: 400;" href="{% url 'KmetApp:register_user' %}">Registracija</a> {% endif %}
                </ul>

            </div>
            <!-- /.navbar-collapse -->
    </nav>
    <!-- Page Header -->
    {% block hdr %}
    <!-- Set your background image for this header on the line below. -->
    <header class="intro-header" style="background-image: url({% static 'img/home-bg.jpg' %})">
        <div class="container">              
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="site-heading">
                        <h1>Veseli kmet</h1>
                        <hr class="small">

                    </div>
                </div>
            </div>
        </div>
    </header>
    {% endblock %} 
    <div class="container">
        {% block content %} {% endblock %}
    </div>
    <hr>

    <!-- Footer -->

    <!-- jQuery -->
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/jquery2.2.4.js' %}"></script>


    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <!-- Custom Theme JavaScript -->
    <script src="{% static 'js/clean-blog.min.js' %}"></script>
    <!-- module -->
</body>

</html>

KmetApp/templates/index.html
{% extends '__base__.html' %}
{% csrf_token %}
{% block prijava %}

 <ul class = "nav navbar-nav navbar-left">
 <li>


{% if user.is_authenticated %}
    <li>
    <a href = "{% url 'KmetApp:logoff' %}">Log Out </a>       
{% else %}
    <li>
    <a href ="{% url 'KmetApp:logon' %}">Prijava </a>

<li>
<a href ="{% url 'KmetApp:register_user' %}">Registracija</a>


{% endif %}
</ul>
{% endblock %}



{% block content %}

<h1>To je veseli kmet</h1>
<p>To je moja vsebina.</p>

{% endblock %}

{% block ftr %}

{% endblock %}